### ISSUE TITLE
Make perldoc_url_prefix configurable

### ISSUE THREAD

**Issue by pjcj** [mgruner/p5-pod-projectdocs#4]
Links to local modules `L<Local::Module>` do not resolve to the local documentation.  It would be lovely if they could, and if the module is not local to default to using _Pod::Simple::XHTML_'s default _perldoc_url_prefix_ value.

It would also be nice to be able to set the _perldoc_url_prefix_ value.

Thanks very much for this module - apart from this gripe it "just works" for me.

**Comment by mgruner** [comment]
Hello @pjcj.

Regarding the first point, can you please explain in more detail what you mean? `L<Local::Module>` should resolve to this module if it is part of the code you're extracting the POD from.

What do you want to achieve by setting the `perldoc_url_prefix`?

Best regards, Martin

**Comment by pjcj** [comment]
Hello Martin,

Thanks for the quick reply.

Perhaps I am doing something wrong, but if I have a bunch of my modules in _/myproj/lib_, for example, and in the pod for _Myproj::Mod1_ I have `L<Myproj::Mod2>`, then on running `pod2projdocs -out /tmp/myprojdoc -lib /myproj/lib` I have, in the HTML for _Myproj::Mod1_, a link to _http://search.cpan.org/perldoc?Myproj::Mod2_ rather than to the local documentation.

And being able to set _perldoc_url_prefix_ means that I can link to metacpan, for instance, rather than search.cpan.org.

**Comment by mgruner** [comment]
@pjcj linking to other modules in the tree is supposed to work. You can see this in action here: http://doc.otrs.com/doc/api/otrs/7.0/Perl/Kernel/System/ObjectManager.pm.html#ObjectRegisterEventHandler (links to `Kernel::System::EventHandler`). There are also test cases for this. Did you check the spelling (case sensitive)?

**Comment by pjcj** [comment]
Urgh, you're absolutely correct, the problem was entirely on my side.  It did seem strange that this wasn't working (for me).  Thanks for helping me clear it up and sorry to have wasted your time there.

I'd still like the _perldoc_url_prefix_ though ;)

**Comment by mgruner** [comment]
NP. Glad we could clarify it. I'll keep this open regarding the prefix.

**Comment by mgruner** [comment]
Is there an url_prefix for metacpan that works in the same way, directly redirecting to the top match? We could also consider using that instead of regular cpan.

**Comment by pjcj** [comment]
The (rejected) pull request to make this change in Pod::Simple at perl-pod/pod-simple#36 and the actual commit is
 https://github.com/perl-pod/pod-simple/pull/36/commits/8241e71e5656668236b5e87f97cf418d727411f6.

So the text to use is `http://metacpan.org/module/`

Thanks!

**Comment by pjcj** [comment]
Lovely, thanks!
