### ISSUE TITLE
No CSS style for =head3 and =head4

### ISSUE THREAD

**Issue by eserte** [mgruner/p5-pod-projectdocs#8]
podstyle.css contains only definitions for ".pod H1" and ".pod H2". However, there's nothing for H3 and H4. This means that default browser styling is used for these, so =head3 appears larger than =head1 (at least in my firefox).

I don't have suggestions how to style ".pod H3" and ".pod H4" best. Maybe H1 could be shifted to x-large, so the next ones could use large, medium, and small (or medium without a special color).

MetaCPAN seems to use 1.5em, 1.3em, 1.1em and 1.1em for H1 .. H4 (that is, no visual difference between =head3 and =head4).

**Comment by mgruner** [comment]
Hello @eserte. Thank you very much for your suggestions. Please have a look at 2cc0b3521b05c71979ed3fc9b2c97db2c2cd85e8, now we have h1 x-large, h2 large, h3 and h4 medium and h4 in italics. I guess this should work, what do you think?

The CSS (and possibly markup) should be overhauled at some point. I'm not a designer though...

**Comment by eserte** [comment]
I tried the latest version from git --- looks fine to me.
